GREEN   = \033[1;32m
WHITE   = \033[0;m

CFLAGS = -O2 -Wall -I../include -nostdlib -nostdinc -fno-builtin -fno-stack-protector

clean:
	@printf "\n[$(GREEN)CLEAN$(WHITE)] INIT\n"
	rm -rf *.o *.d *.bin *.dis *.elf
